language: node_js
node_js:
  - "10"
cache: npm
branches: 
  only:
    - master
install:
  - npm i
script:
  - npm run build
  - npm run docs:build
deploy:
  provider: pages
  local_dir: docs/.vuepress/dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master